Source/DerethForever.Web/Models/Shared/Ability.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DerethForever.Web.Models.Enums;
using Newtonsoft.Json;

namespace DerethForever.Web.Models.Shared
{
    public class Ability
    {
        [JsonProperty("ability")]
        public int AbilityId { get; set; }

        [JsonIgnore]
        public string AbilityIdBinder
        {
            get { return ((AbilityId)AbilityId).GetName(); }
        }

        public AbilityId TypedAbilityId
        {
            get { return (AbilityId)AbilityId; }
        }

        [JsonProperty("baseValue")]
        public uint? Base { get; set; }

        [JsonProperty("ranks")]
        public uint? Ranks { get; set; }

        [JsonProperty("experienceSpent")]
        public uint? ExperienceSpent { get; set; }

        [JsonProperty("startingValue")]
        public uint? UnbuffedValue { get; set; }
    }
}

Source/DerethForever.Web/Models/Shared/Angles.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using Newtonsoft.Json;

namespace DerethForever.Web.Models.Shared
{
    public class Angles
    {
        [JsonProperty("w")]
        public float W { get; set; }

        [JsonProperty("x")]
        public float X { get; set; }

        [JsonProperty("y")]
        public float Y { get; set; }

        [JsonProperty("z")]
        public float Z { get; set; }
    }
}

Source/DerethForever.Web/Controllers/RecipeController.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using System;
using System.Web.Mvc;
using DerethForever.Web.Models.Recipe;

namespace DerethForever.Web.Controllers
{
    public class RecipeController : BaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View(new IndexModel());
        }

        [HttpPost]
        public ActionResult Index(IndexModel model)
        {
            try
            {
                model.Results = SandboxContentProviderHost.CurrentProvider.RecipeSearch(GetUserToken(), model.Criteria);
                model.HasResults = true;
            }
            catch (Exception ex)
            {
                model.Results = null;
                model.HasResults = false;
                model.ErrorMessages.Add("Error retrieving data from the API");
                model.Exception = ex;
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var model = SandboxContentProviderHost.CurrentProvider.GetRecipe(GetUserToken(), id);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Recipe model)
        {
            if (!ModelState.IsValid)
            {
                var errorMessage = string.Empty;
                foreach (ModelState state in ModelState.Values)
                {
                    foreach (ModelError error in state.Errors)
                    {
                        errorMessage += error.ErrorMessage;
                    }
                }

                model.ErrorMessages.Add(errorMessage);
                return View(model);
            }

            model.LastModified = DateTime.Now;
            model.ModifiedBy = GetUserName();

            try
            {
                SandboxContentProviderHost.CurrentProvider.UpdateRecipe(GetUserToken(), model);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                model.ErrorMessages.Add("Error saving recipe in the API");
                model.Exception = ex;
            }

            return View(model);
        }
    }
}

Source/DerethForever.Web/Controllers/WeenieController.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using DerethForever.Web.Models;
using DerethForever.Web.Models.Account;
using DerethForever.Web.Models.CachePwn;
using DerethForever.Web.Models.Discord;
using DerethForever.Web.Models.Enums;
using DerethForever.Web.Models.Shared;
using DerethForever.Web.Models.Weenie;
using log4net;
using Newtonsoft.Json;
using RestSharp;

namespace DerethForever.Web.Controllers
{
    public class WeenieController : BaseController
    {
        private const string _Session_IndexModel = "__weenieIndexModel";
        private const string _Session_DownloadModel = "__weenieDownloadModel";

        private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public IndexModel CurrentIndexModel
        {
            get { return (IndexModel)Session[_Session_IndexModel]; }
            set { Session[_Session_IndexModel] = value; }
        }

        public DownloadChangeModel CurrentDownload
        {
            get { return (DownloadChangeModel)Session[_Session_DownloadModel]; }
            set { Session[_Session_DownloadModel] = value; }
        }

        [HttpGet]
        public ActionResult Recent()
        {
            IndexModel model = CurrentIndexModel ?? new IndexModel();
            model.Results = SandboxContentProviderHost.CurrentProvider.RecentChanges(GetUserToken());

            return View(model);
        }

        [HttpGet]
        public ActionResult Index()
        {
            IndexModel model = CurrentIndexModel ?? new IndexModel();
            BaseModel current = CurrentBaseModel;
            BaseModel.CopyBaseData(current, model);
            CurrentBaseModel = current;

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(IndexModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            try
            {
                model.Results = SandboxContentProviderHost.CurrentProvider.WeenieSearch(GetUserToken(), model.Criteria);

                List<WeenieChange> mine = SandboxContentProviderHost.CurrentProvider.GetMyWeenieChanges(GetUserToken());
                model.Results.ForEach(w =>
                {
                    if (mine.Any(m => m.Weenie.WeenieClassId == w.WeenieClassId))
                        w.HasSandboxChange = true;
                });

                model.ShowResults = true;
            }
            catch (Exception ex)
            {
                model.Results = null;
                model.ShowResults = false;
                model.ErrorMessages.Add("Error retrieving data from the API");
                model.Exception = ex;
            }

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit(uint id)
        {
            Weenie model = SandboxContentProviderHost.CurrentProvider.GetWeenie(GetUserToken(), id);
            SortTheThings(model);

            return View(model);
        }

        private void SortTheThings(Weenie model)
        {
            // Setting sort order for edit
            model.IntProperties = model.IntProperties.OrderBy(ip => ip.IntPropertyId).ToList();
            model.DoubleProperties = model.DoubleProperties.OrderBy(dp => dp.DoublePropertyId).ToList();

            model.EmoteTable.ForEach(t => t.Emotes = t.Emotes.OrderBy(e => e.SortOrder).ToList());
            model.EmoteTable = model.EmoteTable.OrderBy(e => e.EmoteCategoryId).ToList();
        }

        [HttpGet]
        [Authorize]
        public ActionResult Clone(uint id)
        {
            Weenie model = SandboxContentProviderHost.CurrentProvider.GetWeenie(GetUserToken(), id);
            model.WeenieClassId = 0;
            model.DataObjectId = 0;
            ImportedWeenie = model;
            return RedirectToAction("New");
        }

        [HttpGet]
        [Authorize]
        public ActionResult New()
        {
            Weenie model = ImportedWeenie ?? new Weenie();

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult EditImported()
        {
            Weenie model = ImportedWeenie;

            if (model == null)
                RedirectToAction("Upload");

            Weenie existing = SandboxContentProviderHost.CurrentProvider.GetWeenie(GetUserToken(), model.WeenieClassId);
            if (existing == null)
                return RedirectToAction("NewImported");

            SortTheThings(model);

            return View("Edit", model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult NewImported()
        {
            Weenie model = ImportedWeenie;

            if (model == null)
                RedirectToAction("Upload");

            SortTheThings(model);

            return View("New", model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult New(Weenie model)
        {
            ActionResult result = HandlePostback(model);

            if (result != null)
                return result;

            result = ValidateWeenie(model);

            if (result != null)
                return result;

            model.CleanDeletedAndEmptyProperties();
            model.LastModified = DateTime.Now;
            model.ModifiedBy = GetUserName();
            model.DataObjectId = model.WeenieClassId; // both need to be set, only 1 is editable.

            try
            {
                SandboxContentProviderHost.CurrentProvider.CreateWeenie(GetUserToken(), model);

                IndexModel indexModel = new IndexModel();
                indexModel.SuccessMessages.Add("Weenie " + model.WeenieClassId.ToString() + " successfully created.");
                CurrentIndexModel = indexModel;

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                model.ErrorMessages.Add("Error saving weenie in the API");
                model.Exception = ex;
            }

            return View(model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Edit(Weenie model)
        {
            ActionResult result = HandlePostback(model);

            if (result != null)
            {
                ModelState.Clear();
                return result;
            }

            result = ValidateWeenie(model);

            if (result != null)
            {
                ModelState.Clear();
                return result;
            }

            model.CleanDeletedAndEmptyProperties();
            model.LastModified = DateTime.Now;
            model.ModifiedBy = GetUserName();

            try
            {
                SandboxContentProviderHost.CurrentProvider.UpdateWeenie(GetUserToken(), model);

                IndexModel indexModel = new IndexModel();
                indexModel.SuccessMessages.Add("Weenie " + model.WeenieClassId.ToString() + " successfully saved.");
                CurrentIndexModel = indexModel;

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                model.ErrorMessages.Add("Error saving weenie in the API");
                model.Exception = ex;
            }

            return View(model);
        }

        private ActionResult ValidateWeenie(Weenie model)
        {
            bool isValid = true;

            // validatate no duplicate properties
            var dupeInts = model.IntProperties.GroupBy(p => p.IntPropertyId).SelectMany(s => s.Skip(1));
            if (dupeInts.Count() > 0)
            {
                isValid = false;
                dupeInts.ToList().ForEach(dupe => model.ErrorMessages.Add($"Duplicate Int property {dupe.IntPropertyId} - you may only have one."));
            }

            var dupeInt64s = model.Int64Properties.GroupBy(p => p.Int64PropertyId).SelectMany(s => s.Skip(1));
            if (dupeInt64s.Count() > 0)
            {
                isValid = false;
                dupeInt64s.ToList().ForEach(dupe => model.ErrorMessages.Add($"Duplicate Int64 property {dupe.Int64PropertyId} - you may only have one."));
            }

            var dupeDoubles = model.DoubleProperties.GroupBy(p => p.DoublePropertyId).SelectMany(p => p.Skip(1));
            if (dupeDoubles.Count() > 0)
            {
                isValid = false;
                dupeDoubles.ToList().ForEach(dupe => model.ErrorMessages.Add($"Duplicate Double property {dupe.DoublePropertyId} - you may only have one."));
            }

Source/DerethForever.Web/Views/Shared/ServerSelector.cshtml
@using DerethForever.Web.Controllers

@using (Html.BeginForm("SelectServer", "Account", FormMethod.Post))
{
    @Html.Hidden("href", Request.RawUrl)
    if (BaseController.CurrentUser != null)
    {
        @Html.DropDownList("selectedServer", BaseController.CurrentUser.ManagedWorldSelectListItems, BaseController.CurrentUser.SelectedManagedWorld ?? "Select a World", new { @class = "form-control", style = "margin-top: 8px;", onchange = "this.form.submit();" })
    }
}

Source/DerethForever.Web/Views/Shared/WeenieFinder.cshtml
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal well">
        <h4>Weenie Search</h4>
        <hr />

        @if (!string.IsNullOrWhiteSpace(Model.ErrorMessage))
        {
            <div class="alert alert-danger">
                @Html.DisplayFor(m => m.ErrorMessage)
            </div>
        }

        <div class="form-group">
            <label class="control-label col-md-2" for="Criteria_PartialName">Name</label>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Criteria.PartialName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Criteria.PartialName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Criteria_WeenieClassId">Weenie Id</label>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Criteria.WeenieClassId, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Criteria.WeenieClassId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Criteria_ItemType">Item Type</label>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Criteria.ItemType, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Criteria.ItemType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Criteria_WeenieType">Weenie Type</label>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Criteria.WeenieType, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Criteria.WeenieType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </div>

    </div>
    <hr/>

    if (Model.ShowResults)
    {
        if (Model.Results != null)
        { 
            <table class="table table-striped table-bordered table-hover table-condensed">
                <thead>
                    <tr>
                        <th>Weenie Id</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Item Type</th>
                        <th>Weenie Type</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Results.Count == 0)
                    {
                        <tr><td colspan="8" align="center">No results.</td></tr>
                    }
                    @{
                        foreach (var weenie in Model.Results)
                        {
                            <tr>
                                <td>
                                    @Html.ActionLink("[select]", "Edit", "Weenie",  new { id = weenie.WeenieClassId }, new { })
                                    @weenie.WeenieClassId.ToString()
                                </td>
                                <td>
                                    @weenie.Name
                                </td>
                                <td>
                                    @weenie.Description
                                </td>
                                <td>
                                    @weenie.ItemType
                                </td>
                                <td>
                                    @weenie.WeenieType
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        }
        else
        {
            <div class="alert alert-info">
               Your search yielded no results.
            </div>
        }
    }
}

Source/DerethForever.Web/Views/Shared/_Favicons.cshtml
<link rel="apple-touch-icon" sizes="180x180" href="~/images/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="~/images/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="~/images/favicon-16x16.png">
<link rel="manifest" href="~/images/manifest.json">
<link rel="mask-icon" href="~/images/safari-pinned-tab.svg" color="#5bbad5">
<meta name="theme-color" content="#ffffff">

Source/DerethForever.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dereth Forever - @ViewBag.Title</title>
    @Styles.Render("~/Styles/css")
    @Scripts.Render("~/bundles/modernizr")
    @Html.Partial("_Favicons")
</head>

@{
    string ctrl = HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString();
}

<body data-spy="scroll" data-target=".navbar">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Dereth Forever", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li class="@(@ctrl == "Server" ? "active" : "")">@Html.ActionLink("Server Admin", "Index", "Server")</li>
                        <li class="@(@ctrl == "Account" ? "active" : "")">@Html.ActionLink("Accounts", "Accounts", "Account")</li>
                    }
                    <!-- <li class="disabled @(@ctrl == "Content" ? "active" : "")">@Html.ActionLink("Content", "Index", "Content")</li> -->
                    <li class="@(@ctrl == "WorldRelease" ? "active" : "")">@Html.ActionLink("World Releases", "Index", "WorldRelease")</li>
                    <li class="@(@ctrl == "Weenie" ? "active" : "") dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Weenies<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Search", "Index", "Weenie")</li>
                            <li>@Html.ActionLink("Upload JSON Data", "Upload", "Weenie")</li>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li>@Html.ActionLink("My Sandbox", "Sandbox", "Weenie")</li>
                            }
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Developer"))
                            {
                                <li>@Html.ActionLink("Submissions", "Submissions", "Weenie")</li>
                            }
                            <li>@Html.ActionLink("Recent Changes", "Recent", "Weenie")</li>
                            <li>@Html.ActionLink("New", "New", "Weenie")</li>
                        </ul>
                    </li>
                    <!-- <li class="disabled @(@ctrl == "Recipes" ? "active" : "")">@Html.ActionLink("Recipes", "Index", "Recipe")</li> -->
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>
                &copy; @DateTime.Now.Year - Dereth Forever &nbsp;&nbsp;&nbsp;&nbsp;
                <a href="https://www.youtube.com/channel/UC-_zaLe430C2A82Oe6UnTkw" title="Our YouTube Channel"><img src="~/images/youtube_social_icon_red.png" height="24dp" /></a> &nbsp;&nbsp;&nbsp;&nbsp;
                <a href="https://gitlab.com/DerethForever" title="Gitlab"><img src="~/images/gitlab.png" height="35dp" /></a>&nbsp;&nbsp;&nbsp;&nbsp;
                <a href="https://discord.gg/awbXUXF" title="Join us on Discord"><img src="~/images/discord.png" height="35dp" /></a>
            </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>